version: 3

includes:
  build-amd64:
    taskfile: Taskfile.build.yml
    vars:
      ARCH: amd64
  build-arm64:
    taskfile: Taskfile.build.yml
    vars:
      ARCH: arm64

tasks:
  default:
    desc: Список задач
    cmds:
      - task --list

  build-all:
    desc: Сборка проекта
    deps:
      - build-amd64:all
      - build-arm64:all
